use crate::display::text::prelude::*;

pub const FR_DICTIONARY: Dictionary = Dictionary {
    akan_cycle: None,
    armenian: None,
    common_clock: Some(CommonClockDictionary {
        am_full: "Ante Meridiem",
        pm_full: "Post Meridiem",
        am_abr: "AM",
        pm_abr: "PM",
    }),
    coptic: None,
    cotsworth: Some(CotsworthDictionary {
        //https://fr.wikipedia.org/wiki/Mois
        //https://fr.wikipedia.org/wiki/Calendrier_fixe
        january: "janvier",
        february: "février",
        march: "mars",
        april: "avril",
        may: "mai",
        june: "juin",
        sol: "sol",
        july: "juillet",
        august: "août",
        september: "septembre",
        october: "octobre",
        november: "novembre",
        december: "décembre",
        //Epoch
        before_epoch_full: "avant l'ère Cotsworth", //TODO: find the correct one
        after_epoch_full: "l'ère Cotsworth",
        before_epoch_abr: "AEC",
        after_epoch_abr: "EC",
        //Intercalary Days
        year_day: "Jour de l'année",    //TODO: find the correct one
        leap_day: "Journée bissextile", //TODO: find the correct one
    }),
    egyptian: None,
    ethiopic: None,
    french_rev: Some(FrenchRevolutionaryDictionary {
        vendemiaire: "Vendémiaire",
        brumaire: "Brumaire",
        frimaire: "Frimaire",
        nivose: "Nivôse",
        pluviose: "Pluviôse",
        ventose: "Ventôse",
        germinal: "Germinal",
        floreal: "Floréal",
        prairial: "Prairial",
        messidor: "Messidor",
        thermidor: "Thermidor",
        fructidor: "Fructidor",
        primidi: "Primidi",
        duodi: "Duodi",
        tridi: "Tridi",
        quartidi: "Quartidi",
        quintidi: "Quintidi",
        sextidi: "Sextidi",
        septidi: "Septidi",
        octidi: "Octidi",
        nonidi: "Nonidi",
        decadi: "Décadi",
        fete_de_la_vertu: "La Fête de la Vertu",
        fete_du_genie: "La Fête du Génie",
        fete_du_travail: "La Fête du Travail",
        fete_de_lopinion: "La Fête de l'Opinion",
        fete_des_recompenses: "La Fête des Récompenses",
        fete_de_la_revolution: "La Fête de la Révolution",
        before_republic_full: "avant l'ère républicaine",
        after_republic_full: "l'ère républicaine",
        before_republic_abr: "AER",
        after_republic_abr: "ER",
    }),
    gregorian: Some(GregorianDictionary {
        //https://fr.wikipedia.org/wiki/Mois
        //https://fr.wikipedia.org/wiki/%C3%88re_commune
        january: "janvier",
        february: "février",
        march: "mars",
        april: "avril",
        may: "mai",
        june: "juin",
        july: "juillet",
        august: "août",
        september: "septembre",
        october: "octobre",
        november: "novembre",
        december: "décembre",
        //Epoch
        before_common_era_full: "avant l'ère commune",
        common_era_full: "l'ère commune",
        before_common_era_abr: "AEC",
        common_era_abr: "EC",
    }),
    holocene: Some(HoloceneDictionary {
        //https://fr.wikipedia.org/wiki/Mois
        //https://fr.wikipedia.org/wiki/%C3%88re_commune
        january: "janvier",
        february: "février",
        march: "mars",
        april: "avril",
        may: "mai",
        june: "juin",
        july: "juillet",
        august: "août",
        september: "septembre",
        october: "octobre",
        november: "novembre",
        december: "décembre",
        //Epoch
        before_human_era_full: "avant l'ère humaine",
        human_era_full: "l'ère humaine",
        before_human_era_abr: "AEH",
        human_era_abr: "EH",
    }),
    iso: None,
    julian: Some(JulianDictionary {
        //https://fr.wikipedia.org/wiki/Mois
        //https://fr.wikipedia.org/wiki/%C3%88re_chr%C3%A9tienne
        january: "janvier",
        february: "février",
        march: "mars",
        april: "avril",
        may: "mai",
        june: "juin",
        july: "juillet",
        august: "août",
        september: "septembre",
        october: "octobre",
        november: "novembre",
        december: "décembre",
        //Epoch
        before_christ_full: "avant Jésus-Christ",
        anno_domini_full: "après Jésus-Christ",
        before_christ_abr: "av. J.-C.",
        anno_domini_abr: "apr. J.-C.",
    }),
    positivist: Some(PositivistDictionary {
        //https://gallica.bnf.fr/ark:/12148/bpt6k21868f/f42.planchecontact
        //https://gallica.bnf.fr/ark:/12148/bpt6k6108866f/f359.item.zoom
        moses: "Moïse",
        homer: "Homère",
        aristotle: "Aristote",
        archimedes: "Archimède",
        caesar: "Cèsar",
        saint_paul: "Saint-Paul",
        charlemagne: "Charlemagne",
        dante: "Dante",
        gutenburg: "Guttemberg",
        shakespeare: "Shakespeare",
        descartes: "Descartes",
        frederick: "Frédéric",
        bichat: "Bichat",
        before_crisis_full: "avant la Grande Revolution",
        after_crisis_full: "après la Grande Revolution",
        before_crisis_abr: "av. GR",
        after_crisis_abr: "apr. GR",
        festival_of_dead: "La Fête universelle des Morts",
        festival_of_holy_women: "La Fête Générale des Saintes Femmes",
    }),
    roman: None,
    symmetry: Some(SymmetryDictionary {
        january: "janvier",
        february: "février",
        march: "mars",
        april: "avril",
        may: "mai",
        june: "juin",
        july: "juillet",
        august: "août",
        september: "septembre",
        october: "octobre",
        november: "novembre",
        december: "décembre",
        irvember: "irvembre",
        before_epoch_full: "avant l'ère symétrique", //TODO: Proper names
        after_epoch_full: "l'ère symétrique",
        before_epoch_abr: "AES",
        after_epoch_abr: "ES",
    }),
    tranquility: None,
    common_weekday: Some(CommonWeekdayDictionary {
        sunday: "Dimanche",
        monday: "Lundi",
        tuesday: "Mardi",
        wednesday: "Mercredi",
        thursday: "Jeudi",
        friday: "Vendredi",
        saturday: "Samedi",
    }),
};
